fun main() {
    println("Advent of Code")
//    Day1().start()
//    Day2().start()
//    Day3().start()
//    Day4().start()
//    Day5().start()
//    Day6().start()
//    Day7().start()
//    Day8().start()
//    Day9().start()
//    Day10().start()
//    Day11().start()
//    Day12().start()
//    Day13().start()
//    Day14().start()
//    Day15().start()
//    Day16().start()
//    Day17().start()
//    Day18().start()
//    Day19().start()
    Day20().start()
}